# Generated by Django 2.2.4 on 2019-10-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description', models.CharField(max_length=2048)),
                ('minutes', models.IntegerField()),
                ('sms', models.IntegerField()),
                ('traffic', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
