# Generated by Django 2.2.4 on 2019-10-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance_info', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='balance_info.Balance'),
        ),
    ]
