# Generated by Django 2.2.4 on 2019-10-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_profile_phone'),
        ('user_profile', '0002_profile_balance'),
    ]

    operations = [
    ]
