# Generated by Django 2.2.4 on 2019-10-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_merge_20191019_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
    ]
