# Generated by Django 2.2.4 on 2019-10-19 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='balance',
            name='minutes',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
